#!/usr/bin/env bash


###############################################################################################################################
# Function to edit .md files in Haskell project
#!/bin/sh

# Change the directory below to the directory where you want the hook to apply
TARGET_DIR="2th_semester/Haskell"

# Get the list of modified .md files in the specified directory and its subdirectories
MODIFIED_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E "^$TARGET_DIR.*\.md$")

# Add the specified lines to the beginning of each modified .md file
for FILE in $MODIFIED_FILES; do
    # Extract the directory name
    DIRECTORY_NAME=$(basename $(dirname "$FILE"))

    # Add the required lines at the top of the .md file
    TEMP_FILE="$FILE.tmp"
    echo "# FP 3MI0700193" > "$TEMP_FILE"
    echo "### $DIRECTORY_NAME" >> "$TEMP_FILE"
    cat "$FILE" >> "$TEMP_FILE"

    # Replace the original .md file with the modified version
    mv "$TEMP_FILE" "$FILE"

    # Stage the modified .md file for commit
    git add "$FILE"
done
###############################################################################################################################





###############################################################################################################################
# Function to replace "x ^ y" with "x^y" in a Haskell file
format_exponentiation() {
    local file="$1"
    sed -i '' -E 's/([(]*[-0-9a-zA-Z_]+[)]*) *\^ *([(]*[-0-9a-zA-Z_()\\+*\/]+[)]*)/\1^\2/g' "$file"
}

# Find all Haskell source files that are staged for commit
files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.hs$')

# Check if any Haskell files are staged for commit
if [ -z "$files" ]; then
    echo "No Haskell files staged for commit."
    exit 0
fi

echo "Haskell files staged for commit:"
echo "$files"

ormolu_exe="/Users/with/.cabal/bin/ormolu"

# Reformat Haskell files with ormolu and apply the custom exponentiation formatting
for file in $files; do
    echo "Reformatting $file with ormolu..."
    $ormolu_exe -m inplace "$file" || { echo "Ormolu failed for $file. Aborting commit."; exit 1; }
    echo "Applying custom exponentiation formatting to $file..."
    format_exponentiation "$file"
    git add "$file"
    echo "Reformatted and staged $file."
done

echo "All Haskell files reformatted successfully."
exit 0
###############################################################################################################################