@startuml
start
:Заявител подава заявление;

partition "Изпълнителна агенция по лекарствата" {
    :Приемане на заявлението;
    :Проверка на документацията;
    if (Документацията е коректна?) then (yes)
        :Подготовка на административен акт;
    else (no)
        :Изискване на допълнителни документи;
        stop
    endif

    :Издаване на административен акт;
}

partition "Регистър" {
    :Регистрация на заявителя;
}

:Информиране на заявителя за регистрацията;
stop
@enduml
