@startuml
actor Заявител
participant "Изпълнителна\nагенция по лекарствата" as Агенция
participant "Регистър" as Регистър

Заявител -> Агенция: Подава заявление
Агенция -> Агенция: Проверка на документацията
alt Документацията е коректна
    Агенция -> Регистър: Издаване на административен акт
    Регистър -> Регистър: Регистрация на заявителя
    Регистър --> Заявител: Изпращане на уведомление за регистрация
else Документацията е некоректна
    Агенция --> Заявител: Изискване на допълнителни документи
end
@enduml
