@startuml
[*] --> Ново: Заявлението е подадено

state "Ново" as Ново {
    [*] --> В_проверка
    В_проверка -down-> Отхвърлено: Документацията\nе некоректна
    В_проверка --> Одобрено: Документацията\nе коректна
    Отхвърлено --> [*]
}

state "Одобрено" as Одобрено {
    [*] --> В_регистър
    В_регистър -right-> Регистрирано: Регистрация\nв системата
    Регистрирано --> [*]
}

@enduml
